### ISSUE TITLE
[suggestion] Releasing the apk here on Github

### ISSUE THREAD

**Issue by EdoSecco** [SubhamTyagi/android-ocr#96]
I use [Obtainium](https://github.com/ImranR98/Obtainium) and it would be great if you publish the apk in the release section.

Thank you!

**Comment by Boggin** [comment]
I think adding the following to the android.yml may work:
```
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./app/build/outputs/apk/debug/AndroidOCR-debug.apk
          asset_name: AndroidOCR-debug.apk
          asset_content_type: application/vnd.android.package-archive
```
